name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  NEXT_PUBLIC_CONTEMBER_PUBLIC_TOKEN: ${{ secrets.NEXT_PUBLIC_CONTEMBER_PUBLIC_TOKEN }}
  NEXT_PUBLIC_CONTEMBER_CONTENT_URL: ${{ secrets.NEXT_PUBLIC_CONTEMBER_CONTENT_URL }}
  CONTEMBER_ADMIN_TOKEN: ${{ secrets.CONTEMBER_ADMIN_TOKEN }}
  CONTEMBER_LOGIN_TOKEN: ${{ secrets.CONTEMBER_LOGIN_TOKEN }}
  NEXT_PUBLIC_SERVER_URL: ${{ secrets.NEXT_PUBLIC_SERVER_URL }}
  CONTEMBER_PROJECT_SLUG: ${{ secrets.CONTEMBER_PROJECT_SLUG }}
  NEXT_PUBLIC_CONTEMBER_TENANT_URL: ${{ secrets.NEXT_PUBLIC_CONTEMBER_TENANT_URL }}
  NEXT_PUBLIC_TYPESENSE_PROTOCOL: ${{ secrets.NEXT_PUBLIC_TYPESENSE_PROTOCOL }}
  NEXT_PUBLIC_TYPESENSE_HOST: ${{ secrets.NEXT_PUBLIC_TYPESENSE_HOST }}
  NEXT_PUBLIC_TYPESENSE_PORT: ${{ secrets.NEXT_PUBLIC_TYPESENSE_PORT }}
  NEXT_PUBLIC_TYPESENSE_SEARCH_ONLY_API_KEY: ${{ secrets.NEXT_PUBLIC_TYPESENSE_SEARCH_ONLY_API_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm run build
